//
//  ShowBookPresenter.swift
//  Simple
//
//  Created by Dai Doan Van on 10/29/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowBookPresentationLogic
{
  func presentSomething(response: ShowBook.Something.Response)
}

class ShowBookPresenter: ShowBookPresentationLogic
{
  weak var viewController: ShowBookDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowBook.Something.Response)
  {
    let viewModel = ShowBook.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
