//
//  ShowBookInteractor.swift
//  Simple
//
//  Created by Dai Doan Van on 10/29/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowBookBusinessLogic
{
  func doSomething(request: ShowBook.Something.Request)
}

protocol ShowBookDataStore
{
  var book: Book! { get set }
}

class ShowBookInteractor: ShowBookBusinessLogic, ShowBookDataStore
{
  var presenter: ShowBookPresentationLogic?
  var worker: ShowBookWorker?
  var book: Book!
  
  // MARK: Do something
  
  func doSomething(request: ShowBook.Something.Request)
  {
    worker = ShowBookWorker()
    worker?.doSomeWork()
    
    let response = ShowBook.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
